# https://taskfile.dev
#
# Install with:
#
#    sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
#

version: "3"

tasks:
  default:
    cmds:
      - ./configure --prefix=/usr
      - make
      - make install
    silent: false

  install:
    cmds:
      - cmd: |-
          sudo apt-get update \
          && sudo apt-get upgrade -y --no-install-recommends \
          && sudo apt-get install -y --no-install-recommends \
            libncurses6 libncurses-dev \
            autoconf automake libtool build-essential pkg-config \
          && sudo apt-get autoremove
